### ISSUE TITLE
Future of pages that serve primarily to link to a presentation, document or webinar?

### ISSUE THREAD

**Issue by lmz** [tfresource/website#321] opened 2021-03-16 02:17 UTC
e.g.
- Document: https://tfresource.org/topics/TMIP_Activity_Based_Model_Webinar_Series_Instructor_Manual.html
- Presentation: https://tfresource.org/topics/ARC_s_Experience_Using_its_CT_RAMP_Activity_Based_Model.html
- Paper: https://tfresource.org/topics/NCHRP_Synthesis_406_Advanced_Practices_in_Travel_Forecasting_A_Synthesis_of_Highway_Practice.html

The links for these are often broken so I'm wondering if these pages are useful?  I personally thing that unless the item I question has some sort of special significance, it would make more sense to embed them as a direct reference on the relevant topic rather than making these their own pages.

**Comment by gregmacfarlane** [comment] 2021-03-16 15:00
Yes, we made a decision to remove these pages as we encounter them. I had an issue #238 to do this and dumped a lot of things then. But there are others.

**Comment by gregmacfarlane** [comment] 2021-03-16 21:22
Duplicate of #238

**Closed by gregmacfarlane** 2021-03-16 21:22 UTC
